<Project>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).vs\$(SolutionName)\Intermediate\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)Output\</OutputPath>
    <AppendTargetFrameworkToOutputPath>True</AppendTargetFrameworkToOutputPath>
    <Version>3.4.5.8</Version>
    <AvaloniaVersion>12.0.4</AvaloniaVersion>
  </PropertyGroup>
</Project>
