<Project>
  <PropertyGroup>
    <Company>https://codewf.com</Company>
    <Authors>沙漠尽头的狼</Authors>
    <Owners>https://codewf.com</Owners>
    <Description>CodeWF.EventBus 提供轻量事件总线能力，支持在 WPF、WinForms、Avalonia 和 ASP.NET Core 等项目中实现发布订阅、CQRS 读写分离和模块间解耦。</Description>
    <ApplicationIcon>$(MSBuildThisFileDirectory)logo.ico</ApplicationIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>$(AssemblyName)</Title>
    <Copyright>Copyright © https://codewf.com 2026</Copyright>
    <AssemblyName>$(AssemblyName)</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageTags>csharp eventbus cqrs pubsub wpf winforms avalonia aspnetcore</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/dotnet9/CodeWF.EventBus</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dotnet9/CodeWF.EventBus</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)logo.png" Pack="true" PackagePath="" Link="logo.png" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>
</Project>