<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\CodeWF.EventBus\\CodeWF.EventBus.csproj" />
  </ItemGroup>
</Project>