<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <RootNamespace>WindowsFormsApp1_4_8</RootNamespace>
    <AssemblyName>WindowsFormsApp1_4_8</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeWF.EventBus\CodeWF.EventBus.csproj" />
  </ItemGroup>
</Project>
