<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<PublishAot>true</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<TrimmerRootDescriptor Include="Roots.xml" />
	</ItemGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="CodeWF.LogViewer.Avalonia" />
		<PackageReference Include="Semi.Avalonia" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\CodeWF.EventBus\CodeWF.EventBus.csproj" />
	</ItemGroup>
</Project>
