<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <TrimmerRootDescriptor Include="Roots.xml" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="..\..\logo.ico" Link="Assets\logo.ico" />
    <AvaloniaResource Include="..\..\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\..\logo.svg" Link="Assets\logo.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="CodeWF.Log.Avalonia" />
    <PackageReference Include="Semi.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeWF.EventBus\CodeWF.EventBus.csproj" />
  </ItemGroup>
</Project>
